#Service Name and Port
spring:
  application:
  name: insurance-client
  #Connect Client to the Config Server
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9090

app:
  message: I am having Production Configurations

insurance:
  provider:
    url: http://localhost:8080/insurance-service/getUpdatePlansList
